name: release

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Tests
        run: npm test

      - name: Upload package artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: npm-package-artifact
          path: build
          if-no-files-found: error
          retention-days: 7

  publish:
    needs: build-release-artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      id-token: write # to enable use of OIDC for npm provenance
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Download package artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: npm-package-artifact
          path: build

      - name: Install release tooling
        run: npm ci --ignore-scripts

      - name: Setup Git
        run: |
          git config --local user.name "Artem Zakharchenko"
          git config --local user.email "kettanaito@gmail.com"

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          NPM_CONFIG_IGNORE_SCRIPTS: true
